### ISSUE TITLE
Possible to move to orbitdb org?

### ISSUE THREAD

**Issue by aphelionz** [haadcode/ipfs-pubsub-peer-monitor#2]
Like my issue in `ipfs-pubsub-1on1`, I'd like to do some heavy work on this to get it up to date with the latest IPFS versions, and take care of the issues expressed in the PRs. Would it be possible to grant me access to this repo or (preferably) move this to `orbitdb`?

**Comment by haadcode** [comment]
Ping @achingbrain @satazor @hacdias (not sure who is admin in this org atm).

Would love to get these either transfered, or at least have the possibility to add contributors/change settings (if they stay in this org).

**Comment by aphelionz** [comment]
Forked it for now, happy to migrate back to this in the future.

**Comment by achingbrain** [comment]
Sorry - I missed this. I have no objection to moving this to the orbitdb org.

**Comment by aphelionz** [comment]
Cool, lmk how I can facilitate

**Comment by haadcode** [comment]
@achingbrain mind giving me admin access so we can move the repo?

**Comment by hacdias** [comment]
Ping @ipfs-shipyard/github-mgmt-stewards.

**Comment by achingbrain** [comment]
@haadcode you should now have admin privileges and be able to move this repo 👍

**Comment by aphelionz** [comment]
`ipfs-pubsub-room` too, perhaps? 🙏
